name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  client-tests:
    name: Run Client Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/build_and_release_setup_env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test-all

  server-tests:
    name: Run Server Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/build_and_release_setup_env

      - name: Install dependencies
        run: cd server && yarn install --frozen-lockfile

      - name: Run tests
        run: cd server && yarn test-all
